name: 01 - Building Blocks

on: push

jobs:
  echo-hello:
    runs-on: ubunto-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
  echo-goodbye:
    runs-on: ubunto-lates
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!"
