name: 01 - Building Blocks

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubunto-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
  echo-goodbye:
    runs-on: ubunto-lates
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"
